#! /bin/sh

#Padding on top
bspc config -m DisplayPort-0 top_padding -6
bspc config -m DisplayPort-0 bottom_padding -6

bspc config -m DVI-0 top_padding -6
bspc config -m DVI-0 bottom_padding -6

bspc config -m DisplayPort-0   border_width        4
bspc config -m DVI-0           border_width        4

bspc config -m DisplayPort-0   window_gap          2
bspc config -m DVI-0	       window_gap            2

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color "#00AA00"

bspc monitor -d I II III IV

bspc rule -a "crx_nckgahadagoaajjgafhacjanaoiihapd" floating=on
bspc rule -a "crx_knipolnnllmklapflnccelgolnpehhpl" floating=on
#bspc rule -a "Steam" floating=on
bspc rule -a "vlc" floating=on
bspc rule -a "Xenonauts.exe" floating=on
#bspc rule -a "feh" floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
